<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Rental_Project_2026.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\ACCOU\**" />
    <EmbeddedResource Remove="Entities\ACCOU\**" />
    <None Remove="Entities\ACCOU\**" />
  </ItemGroup>

</Project>
