// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Rental_Project_2026.Persistence;

#nullable disable

namespace Rental_Project_2026.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260530093000_AddPaymentsModule")]
    partial class AddPaymentsModule
    {
    }
}
